### ISSUE TITLE
"Attempt to free invalid pointer" on Cray

### ISSUE THREAD

**Issue by timrlaw** [LLNL/Caliper#120]
Hi,

I'm trying to use Caliper on a Cray XC30 ([ARCHER](http://www.archer.ac.uk/)). The environment is as follows:

```
modules/3.2.10.6
eswrap/1.3.3-1.020200.1280.0
switch/1.0-1.0502.60522.1.61.ari
cce/8.6.5
craype-network-aries
craype/2.5.10
cray-libsci/16.11.1
udreg/2.3.2-1.0502.10518.2.17.ari
ugni/6.0-1.0502.10863.8.29.ari
pmi/5.0.13
dmapp/7.0.1-1.0502.11080.8.76.ari
gni-headers/4.0-1.0502.10859.7.8.ari
xpmem/0.1-2.0502.64982.5.3.ari
dvs/2.5_0.9.0-1.0502.2188.1.116.ari
alps/5.2.4-2.0502.9774.31.11.ari
rca/1.0.0-2.0502.60530.1.62.ari
atp/2.1.0
PrgEnv-cray/5.2.82
pbs/12.2.401.141761
craype-ivybridge
cray-mpich/7.7.0
packages-archer
bolt/0.6
nano/2.2.6
leave_time/1.3.0
quickstart/1.0
ack/2.14
xalt/0.6.0
openssl/1.1.0g_build1
curl/7.58.0_build1
git/2.16.2_build1
epcc-tools/8.0
cmake/3.10.2
pcre/8.35
```

I build Caliper like this (all static libraries as the platform doesn't advise dynamic linking):

```
git clone https://github.com/LLNL/Caliper caliper
cd caliper
git checkout v1.7.0
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=$HOME -DBUILD_SHARED_LIBS=OFF -DWITH_MPI=ON -DWITH_GOTCHA=OFF ..
make && make install
```

(I disable GOTCHA as Cray doesn't like the -fvisibility flags. I've tried building Caliper with GOTCHA and manually disabling these flags, and it builds but gives the same end problem).

I've successfully used Caliper with my application on other machines, but here when I run the application terminates immediately with the following errors and backtrace:

Error:

```
craylibs//google-perftools/src/tcmalloc.cc:644] Attempt to free invalid pointer: 0x4000000000000000
craylibs//google-perftools/src/tcmalloc.cc:644] Attempt to free invalid pointer: 0x4000000000000000
craylibs//google-perftools/src/tcmalloc.cc:644] Attempt to free invalid pointer: 0x4000000000000000
craylibs//google-perftools/src/tcmalloc.cc:644] Attempt to free invalid pointer: 0x4000000000000000
_pmiu_daemon(SIGCHLD): [NID 02550] [c5-1c0s13n2] [Sat Jun 30 15:37:31 2018] PE RANK 0 exit signal Aborted
[NID 02550] 2018-06-30 15:37:31 Apid 31272615: initiated application termination
```

Backtrace:

```
#0  0x000000000069e8ab in raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:42
#1  0x0000000000adde31 in abort () at abort.c:92
#2  0x0000000000acd1a9 in TCMalloc_CRASH_internal(bool, char const*, int, char const*, __va_list_tag*) ()
#3  0x0000000000acd444 in TCMalloc_CrashReporter::PrintfAndDie(char const*, ...) ()
#4  0x0000000000ac9ebe in (anonymous namespace)::InvalidFree(void*) ()
#5  0x0000000000b6f07d in tc_deletearray ()
#6  0x0000000000403f8b in void std::_Destroy_aux<false>::__destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) ()
    at /opt/gcc/6.1.0/snos/include/g++/bits/stl_construct.h:103
#7  0x0000000000403cf9 in std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~vector() () at /opt/gcc/6.1.0/snos/include/g++/bits/stl_vector.h:426
#8  0x00000000005e4a06 in AggregateDB::init_static_data() () at /.../timrlaw/repos/caliper/src/services/aggregate/Aggregate.cpp:415
#9  0x00000000005e70bc in AggregateDB::aggregate_register(cali::Caliper*) () at /.../timrlaw/repos/caliper/src/services/aggregate/Aggregate.cpp:844
#10 0x00000000005d1a53 in cali::Services::ServicesImpl::register_services(cali::Caliper*) () at /.../timrlaw/repos/caliper/src/services/Services.cpp:106
#11 0x00000000005b9e44 in cali::Caliper::GlobalData::init() () at /.../timrlaw/repos/caliper/src/caliper/Caliper.cpp:327
#12 0x00000000005b909f in cali::Caliper::GlobalData::GlobalData() () at /.../timrlaw/repos/caliper/src/caliper/Caliper.cpp:269
#13 0x00000000005b825f in cali::Caliper::instance() () at /.../timrlaw/repos/caliper/src/caliper/Caliper.cpp:1358
#14 0x00000000005b50da in cali::Caliper::Caliper() () at /.../timrlaw/repos/caliper/src/caliper/Caliper.cpp:1324
#15 0x00000000005acba1 in cali::Function::Function(char const*) () at /.../timrlaw/repos/caliper/src/caliper/Annotation.cpp:59
#16 0x0000000000401cad in main () at ...
```

Any ideas?

Thanks,
Tim

**Comment by timrlaw** [comment]
Seems to be a standard library issue, the following blows up in the same way:

```
struct A
{
    static std::vector<std::string> sv;
};

std::vector<std::string> A::sv;

int main(int argc, char **argv)
{
    A::sv = std::vector<std::string>(10); // attempt to free invalid pointer when destructing the original
    return 0;
}
```

**Comment by daboehme** [comment]
Interesting. I haven't seen this before, but thanks for investigating this @timrlaw
